project:
  type: website
  output-dir: docs

website:
  title: "Hector Zumbado-Ulate"
  navbar:
    background: "#C45508"
    right:
      - about.qmd
      - intro.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      dark: quartz
      light: cosmo
    css: styles.css
    highlight-style: espresso

editor: visual

